/**
 * Bundle size report.
 *
 * Bundles realistic consumer scenarios against the built `dist/` output with
 * esbuild, measures minified and gzipped bytes, prints a table, writes
 * `size-report.md` (used by CI to comment on PRs), and fails if any scenario
 * exceeds its budget.
 *
 * Usage: npm run build && node scripts/check-size.mjs
 */
import { build } from 'esbuild';
import { gzipSync } from 'node:zlib';
import { writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Budgets are minified (pre-gzip) bytes. Raise them consciously in the same
 * PR that grows the bundle; CI fails when they're exceeded.
 */
const SCENARIOS = [
  {
    name: 'core: KeybindingService only',
    code: `import { KeybindingService } from './dist/index.js'; console.log(KeybindingService);`,
    budget: 5_250,
  },
  {
    name: 'core: all three services',
    code: `import { KeybindingService, MouseBindingService, PointerBindingService } from './dist/index.js'; console.log(KeybindingService, MouseBindingService, PointerBindingService);`,
    budget: 9_250,
  },
  {
    name: 'core: everything (incl. parse/format)',
    code: `export * from './dist/index.js';`,
    budget: 11_500,
  },
  {
    name: 'react adapter (all hooks, react external)',
    code: `export * from './dist/react/index.js';`,
    budget: 12_500,
    external: ['react'],
  },
];

async function measure(scenario) {
  const result = await build({
    stdin: {
      contents: scenario.code,
      resolveDir: root,
      sourcefile: 'entry.mjs',
    },
    bundle: true,
    minify: true,
    format: 'esm',
    write: false,
    external: scenario.external ?? [],
    logLevel: 'silent',
  });
  const output = result.outputFiles[0].contents;
  return { min: output.byteLength, gzip: gzipSync(output, { level: 9 }).byteLength };
}

function kb(bytes) {
  return `${(bytes / 1024).toFixed(2)} KB`;
}

if (!existsSync(resolve(root, 'dist/index.js'))) {
  console.error('dist/index.js not found — run `npm run build` first.');
  process.exit(1);
}

const rows = [];
let failed = false;
for (const scenario of SCENARIOS) {
  const { min, gzip } = await measure(scenario);
  const over = min > scenario.budget;
  failed ||= over;
  rows.push({ name: scenario.name, min, gzip, budget: scenario.budget, over });
}

const header = '| Scenario | Minified | Gzipped | Budget | Status |';
const sep = '|---|---:|---:|---:|:---:|';
const lines = rows.map(
  (r) =>
    `| ${r.name} | ${kb(r.min)} | ${kb(r.gzip)} | ${kb(r.budget)} | ${r.over ? '❌ over' : '✅'} |`
);
const table = [header, sep, ...lines].join('\n');
const markdown = `### 📦 Bundle size\n\n${table}\n\n_Minified with esbuild; budgets apply to minified size. Generated by \`scripts/check-size.mjs\`._\n`;

console.log(markdown);
writeFileSync(resolve(root, 'size-report.md'), markdown);

if (process.env.GITHUB_STEP_SUMMARY) {
  writeFileSync(process.env.GITHUB_STEP_SUMMARY, markdown, { flag: 'a' });
}

if (failed) {
  console.error('\nBundle size budget exceeded.');
  process.exit(1);
}
