/**
 * Bundle size report.
 *
 * Bundles realistic consumer scenarios from `scripts/size-scenarios/*.mjs`
 * against the built `dist/` output with esbuild, measures minified and gzipped
 * bytes, writes minified artifacts to `scripts/size-scenarios/.out/` for
 * inspection, prints a table, writes `size-report.md` (used by CI to comment
 * on PRs), and fails if any scenario exceeds its budget.
 *
 * Usage: npm run build && node scripts/check-size.mjs
 */
import { build } from 'esbuild';
import { gzipSync } from 'node:zlib';
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const scenariosDir = resolve(root, 'scripts/size-scenarios');
const outDir = resolve(scenariosDir, '.out');

/**
 * Budgets are minified (pre-gzip) bytes. Raise them consciously in the same
 * PR that grows the bundle; CI fails when they're exceeded.
 */
const SCENARIOS = [
  { file: 'core-keybindings.mjs', name: 'core: keybindings only (no chords)', budget: 3_500 },
  { file: 'core-chords.mjs', name: 'core: keybindings + chords', budget: 4_200 },
  // Pointer budgets raised for the buttonless-kind overload (arg
  // normalization + legacy dual-hash dispatch), ~450 B minified.
  { file: 'core-keyboard-pointer.mjs', name: 'core: keyboard + pointer', budget: 5_800 },
  { file: 'core-everything.mjs', name: 'core: everything (incl. parse/format)', budget: 8_700 },
  {
    file: 'react-keybinding-only.mjs',
    name: 'react: useKeybinding only (react external)',
    budget: 4_700,
    external: ['react'],
  },
  {
    file: 'react-chord-only.mjs',
    name: 'react: useChordKeybinding only (react external)',
    budget: 5_100,
    external: ['react'],
  },
  {
    file: 'react-parsed-only.mjs',
    name: 'react: useParsedKeybinding only (react external)',
    budget: 6_800,
    external: ['react'],
  },
  {
    file: 'react-pointer-only.mjs',
    name: 'react: usePointerBinding only (react external)',
    budget: 5_700,
    external: ['react'],
  },
  {
    file: 'react-keybinding-pointer.mjs',
    name: 'react: useKeybinding + usePointerBinding (react external)',
    budget: 7_800,
    external: ['react'],
  },
  {
    file: 'react-all-hooks.mjs',
    name: 'react: all hooks (react external)',
    budget: 9_900,
    external: ['react'],
  },
];

async function measure(scenario) {
  const entry = resolve(scenariosDir, scenario.file);
  const result = await build({
    entryPoints: [entry],
    bundle: true,
    minify: true,
    format: 'esm',
    write: false,
    external: scenario.external ?? [],
    define: { 'process.env.NODE_ENV': '"production"' },
    logLevel: 'silent',
  });
  const output = result.outputFiles[0].contents;
  return { min: output.byteLength, gzip: gzipSync(output, { level: 9 }).byteLength, code: output };
}

function kb(bytes) {
  return `${(bytes / 1024).toFixed(2)} KB`;
}

if (!existsSync(resolve(root, 'dist/index.js'))) {
  console.error('dist/index.js not found — run `npm run build` first.');
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });

const rows = [];
let failed = false;
for (const scenario of SCENARIOS) {
  const { min, gzip, code } = await measure(scenario);
  const over = min > scenario.budget;
  failed ||= over;
  rows.push({ name: scenario.name, min, gzip, budget: scenario.budget, over });

  const outName = basename(scenario.file, '.mjs') + '.min.js';
  writeFileSync(resolve(outDir, outName), code);
}

const header = '| Scenario | Minified | Gzipped | Budget | Status |';
const sep = '|---|---:|---:|---:|:---:|';
const lines = rows.map(
  (r) =>
    `| ${r.name} | ${kb(r.min)} | ${kb(r.gzip)} | ${kb(r.budget)} | ${r.over ? '❌ over' : '✅'} |`
);
const table = [header, sep, ...lines].join('\n');
const markdown = `### 📦 Bundle size\n\n${table}\n\n_Minified with esbuild; budgets apply to minified size. Artifacts written to \`scripts/size-scenarios/.out/\`. Generated by \`scripts/check-size.mjs\`._\n`;

console.log(markdown);
writeFileSync(resolve(root, 'size-report.md'), markdown);

if (process.env.GITHUB_STEP_SUMMARY) {
  writeFileSync(process.env.GITHUB_STEP_SUMMARY, markdown, { flag: 'a' });
}

if (failed) {
  console.error('\nBundle size budget exceeded.');
  process.exit(1);
}
